[[actions]]
name = "play"
path = "Don't Wake Up.exe"
platform = "windows"

[[actions]]
name = "play"
path = "Don't Wake Up"
platform = "linux"

[[actions]]
name = "play"
path = "Don't Wake Up"
platform = "osx"